spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall4cloud_order?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1200000
      connection-test-query: SELECT 1
      validation-timeout: 5000
      data-source-properties:
        socketTimeout: 60000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        jdbc:
          timeout: 60

server:
  port: 8080

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
